import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
function App(){const[s,setS]=useState<any>(null);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[username,setUsername]=useState('');const[groups,setGroups]=useState<any[]>([]);const[active,setActive]=useState<any>(null);const[tab,setTab]=useState('chat');const[messages,setMessages]=useState<any[]>([]);const[tasks,setTasks]=useState<any[]>([]);
useEffect(()=>{supabase.auth.getSession().then(x=>setS(x.data.session));return supabase.auth.onAuthStateChange((_,x)=>setS(x)).data.subscription.unsubscribe},[]);
useEffect(()=>{if(s)loadGroups()},[s]);
async function auth(signup:boolean){const r=signup?await supabase.auth.signUp({email,password,options:{data:{username}}}):await supabase.auth.signInWithPassword({email,password});if(r.error)alert(r.error.message)}
async function loadGroups(){const{data}=await supabase.from('groups').select('*').order('created_at',{ascending:false});setGroups(data||[])}
async function createGroup(){const name=prompt('Group name');if(!name)return;const description=prompt('Description')||'';const{error}=await supabase.from('groups').insert({name,description,created_by:s.user.id});if(error)alert(error.message);loadGroups()}
async function open(g:any){setActive(g);const[m,t]=await Promise.all([supabase.from('messages').select('*,profiles(username)').eq('group_id',g.id).order('created_at'),supabase.from('tasks').select('*').eq('group_id',g.id).order('created_at',{ascending:false})]);setMessages(m.data||[]);setTasks(t.data||[])}
async function join(g:any){const r=await supabase.from('group_members').insert({group_id:g.id,user_id:s.user.id});if(r.error&&!r.error.message.includes('duplicate'))alert(r.error.message);open(g)}
async function send(){if(!active)return;const content=prompt('Message');if(content){const r=await supabase.from('messages').insert({group_id:active.id,user_id:s.user.id,content});if(r.error)alert(r.error.message);else open(active)}}
async function task(){if(!active)return;const title=prompt('Task title');if(!title)return;const description=prompt('Task details')||'';const r=await supabase.from('tasks').insert({group_id:active.id,title,description,created_by:s.user.id});if(r.error)alert('Only admins can create tasks');else open(active)}
if(!s)return <main className="auth"><h1>TeerWon</h1><p>Groups · Tasks · Chat</p><input placeholder="Username for signup" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>auth(false)}>Login</button><button onClick={()=>auth(true)}>Create account</button></main>;
if(!active)return <main><header>TeerWon <button onClick={()=>supabase.auth.signOut()}>Logout</button></header><section><button onClick={createGroup}>＋ Create group</button>{groups.map(g=><article key={g.id} onClick={()=>open(g)}><h3>{g.name}</h3><p>{g.description}</p><button onClick={e=>{e.stopPropagation();join(g)}}>Join / Open</button></article>)}</section></main>;
return <main><header><button onClick={()=>setActive(null)}>←</button>{active.name}</header><nav><button onClick={()=>setTab('chat')}>Chat</button><button onClick={()=>setTab('tasks')}>Tasks</button></nav>{tab==='chat'?<section>{messages.map(m=><div className="message" key={m.id}><b>{m.profiles?.username||'User'}</b><br/>{m.content}</div>)}<button className="fab" onClick={send}>＋</button></section>:<section><button onClick={task}>＋ Create task</button>{tasks.map(t=><article key={t.id}><h3>{t.title}</h3><p>{t.description}</p></article>)}</section>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);